### ISSUE TITLE
按快速启动配置后运行chatdacs.exe闪退

### ISSUE THREAD

**Issue by kamesan012** [Giftia/ChatDACS#114]
具体原因未知，已知配置完成后可正常运行go-cqhttp_windows_amd64.exe

**Comment by Giftia** [comment]
@kamesan012 您好，现在actions已经有一份最新成功构建包 https://github.com/Giftia/ChatDACS/actions/runs/2051388745 ，麻烦测试一下，我这边测试现在没有问题了

**Comment by kamesan012** [comment]
> @kamesan012 您好，现在actions已经有一份最新成功构建包 https://github.com/Giftia/ChatDACS/actions/runs/2051388745 ，麻烦测试一下，我这边测试现在没有问题了

还是会闪退，对node版本有要求吗

**Comment by Giftia** [comment]
感谢 @kamesan012 您的反馈，我会提起一个 pull request ：在程序根目录增加`启动路径不得存在中文`的提示 用以 为您在本项目中进行贡献

**Comment by ssp97** [comment]
中文路径不是之前在程序里做了个提示避免闪退吗，被你删掉了？ @Giftia https://github.com/Giftia/ChatDACS/commit/f668341424d5f42e567da7a05aeeac2c55537897

**Comment by Giftia** [comment]
> 中文路径不是之前在程序里做了个提示避免闪退吗，被你删掉了？ @Giftia [f668341](https://github.com/Giftia/ChatDACS/commit/f668341424d5f42e567da7a05aeeac2c55537897)

避免闪退的提示闪退了😅
